"""Offline tests for the CoinAPI reviewed-manifest backfill planning core
(`ingest/coinapi_backfill.py`, issue #53). Stdlib-only module, synthetic manifests generated by
the REAL reviewer (tests/coinapi_backfill_fixtures.py) — no vendor I/O anywhere.

Covers: the fail-closed acceptance gate (ready/scope-complete/hash/stale/malformed), sparse unit
derivation (exact fill units, never intervening dates), verbatim stitch/provenance preservation,
sections + cost reconciliation against the reviewed manifest, the hash-pinned pilot-window subset,
resume-state keying on source/product/day + manifest fingerprint, and execution-report
reconciliation."""
import json
import os
import pathlib as _pl
import sys

import pytest

sys.path.insert(0, str(_pl.Path(__file__).resolve().parent))
import coinapi_backfill_fixtures as fx  # noqa: E402

bf = fx.load_by_path("coinapi_backfill", "ingest/coinapi_backfill.py")


def _plan(path, **kw):
    kw.setdefault("generated_utc", "2026-07-10T01:00:00Z")
    return bf.build_plan(str(path), **kw)


def _units_by_key(plan):
    return {(u["product"], u["day"]): u for u in plan["units"]}


# =========================================================================== contract pins
def test_pinned_keys_aligned_with_reviewer():
    assert set(bf.BLOCKER_KEYS) == set(fx.rv.BLOCKER_KEYS)
    assert set(bf.SECTION_KEYS) == set(fx.rv._sections([]))
    assert bf.MANIFEST_VERSION == fx.rv.MANIFEST_VERSION


# =========================================================================== acceptance gate
def test_accepts_ready_manifest_and_derives_exact_sparse_units(tmp_path):
    path, manifest = fx.ready_manifest(tmp_path)
    plan = _plan(path)
    keys = [(u["product"], u["day"]) for u in plan["units"]]
    assert keys == [("limitbook_full", "2025-01-02"),
                    ("limitbook_full", "2025-01-03"),
                    ("limitbook_full", "2025-01-10"),
                    ("trades", "2025-01-10"),
                    ("trades", "2025-01-11")]
    # intervening non-fill dates and non-fill days never become units
    unit_days = {u["day"] for u in plan["units"]}
    for absent in ("2025-01-01", "2025-01-04", "2025-01-05", "2025-01-09", "2025-01-20"):
        assert absent not in unit_days or absent in ("2025-01-10", "2025-01-11")
    assert all(u["source"] == "coinapi_flatfiles" for u in plan["units"])
    assert plan["meta"]["manifest"]["sha256"] == bf.sha256_file(str(path))
    assert plan["meta"]["manifest"]["status"] == "ready"
    assert plan["plan_version"] == 1


def test_unit_kinds_and_cost_basis(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    units = _units_by_key(_plan(path))
    assert units[("limitbook_full", "2025-01-02")]["kind"] == "full_day"
    assert units[("limitbook_full", "2025-01-03")]["kind"] == "partial"
    assert units[("limitbook_full", "2025-01-10")]["kind"] == "full_day"
    assert units[("trades", "2025-01-10")]["kind"] == "full_day"
    # measured where the calendar probed, conservative estimate otherwise
    assert units[("limitbook_full", "2025-01-10")]["gb_basis"] == "measured"
    assert units[("limitbook_full", "2025-01-10")]["gb"] == 1.0
    assert units[("limitbook_full", "2025-01-02")]["gb_basis"] == "estimated"
    assert units[("limitbook_full", "2025-01-02")]["gb"] == 2.27
    assert units[("trades", "2025-01-11")]["gb"] == 0.02


def test_partial_day_stitch_metadata_preserved_verbatim(tmp_path):
    path, manifest = fx.ready_manifest(tmp_path)
    day = {r["day"]: r for r in manifest["days"]}
    units = _units_by_key(_plan(path))
    prov = units[("limitbook_full", "2025-01-03")]["provenance"]
    assert prov["fill"] == day["2025-01-03"]["book_fill"]           # verbatim, deep-equal
    assert prov["fill"]["fill_profile"] == "leading_partial_fill"
    assert prov["fill"]["seams"] == day["2025-01-03"]["book_fill"]["seams"]
    assert prov["fill"]["seam_policy"] == day["2025-01-03"]["book_fill"]["seam_policy"]
    assert prov["fill"]["trusted_lake_start_ts"] is not None
    assert prov["classification"] == "lake_present_degraded"
    # calendar-gap synthesized plan rides along verbatim too
    gap = units[("limitbook_full", "2025-01-10")]["provenance"]
    assert gap["fill"] == day["2025-01-10"]["book_fill"]
    assert gap["fill"]["why"] == "calendar_book_gap"
    # trades provenance carries the trade_fill block verbatim
    tr = units[("trades", "2025-01-11")]["provenance"]
    assert tr["fill"] == day["2025-01-11"]["trade_fill"]


def test_totals_reconcile_with_manifest_cost_summary(tmp_path):
    path, manifest = fx.ready_manifest(tmp_path)
    plan = _plan(path)
    t, cs = plan["totals"], manifest["cost_summary"]
    assert t["n_units"] == 5
    assert t["book_units"] == cs["book_fill_days"] == 3
    assert t["book_full_days"] == cs["full_book_fill_days"] == 2
    assert t["book_partial_days"] == cs["partial_book_fill_days"] == 1
    assert t["trade_units"] == cs["trade_fill_days"] == 2
    assert t["book_gb_measured"] == cs["book_gb_measured"]
    assert t["book_gb_estimated"] == cs["book_gb_estimated"]
    assert t["book_gb_total"] == cs["book_gb_total"]
    assert t["trades_gb_total"] == cs["trades_gb_total"]
    assert t["book_usd"] == cs["book_usd"]
    assert t["trades_usd"] == cs["trades_usd"]
    assert t["gross_usd"] == cs["gross_usd"]
    assert t["usd_high"] == cs["band"]["high_usd"]
    assert t["usd_low"] == cs["band"]["low_usd"]
    assert plan["reconciliation"]["matches_manifest_cost_summary"] is True
    assert plan["reconciliation"]["issues"] == []


def test_refuses_blocking_manifest(tmp_path):
    path, _ = fx.blocking_manifest(tmp_path)
    with pytest.raises(bf.BackfillRefusal, match="status"):
        _plan(path)


def test_refuses_ready_status_with_nonempty_blockers(tmp_path):
    path, _ = fx.blocking_manifest(tmp_path)
    def relabel(m):
        m["meta"]["status"] = "ready"
        m["meta"]["scope_complete"] = True
    fx.mutate_manifest(path, relabel)
    with pytest.raises(bf.BackfillRefusal, match="blocker"):
        _plan(path, verify_inputs=False)


def test_refuses_unresolved_day_even_if_relabeled(tmp_path):
    path, _ = fx.blocking_manifest(tmp_path)
    def relabel(m):
        m["meta"]["status"] = "ready"
        m["meta"]["scope_complete"] = True
        m["blockers"] = {k: [] for k in m["blockers"]}
        m["sections"]["unresolved_days"] = []
    fx.mutate_manifest(path, relabel)
    with pytest.raises(bf.BackfillRefusal, match="unresolved"):
        _plan(path, verify_inputs=False)


@pytest.mark.parametrize("mutator,match", [
    (lambda m: m["meta"].update(scope_complete=False), "scope_complete"),
    (lambda m: m.update(manifest_version=2), "manifest_version"),
    (lambda m: m["meta"].update(kind="something_else"), "kind"),
    (lambda m: m["meta"].update(exchange="BINANCE"), "exchange"),
    (lambda m: m["sections"].pop("trade_fills"), "sections"),
    (lambda m: m.pop("blockers"), "blocker"),
    (lambda m: m["meta"].pop("cost_model"), "cost_model"),
    (lambda m: m.update(days=[]), "days"),
])
def test_refuses_incomplete_or_malformed_manifest(tmp_path, mutator, match):
    path, _ = fx.ready_manifest(tmp_path)
    fx.mutate_manifest(path, mutator)
    with pytest.raises(bf.BackfillRefusal, match=match):
        _plan(path, verify_inputs=False)


def test_refuses_manifest_hash_mismatch(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    with pytest.raises(bf.BackfillRefusal, match="sha256"):
        _plan(path, expected_sha256="0" * 64)


@pytest.mark.parametrize("bad_gb", ["abc", None, [1], True])
def test_refuses_malformed_gb_cleanly(tmp_path, bad_gb):
    # a malformed gb must be a clean refusal, never a raw ValueError/TypeError from the cost math
    path, _ = fx.ready_manifest(tmp_path)
    def poison(m):
        for r in m["days"]:
            if r["day"] == "2025-01-02":
                r["book_fill"]["gb"] = bad_gb
    fx.mutate_manifest(path, poison)
    with pytest.raises(bf.BackfillRefusal, match="gb"):
        _plan(path, verify_inputs=False)


@pytest.mark.parametrize("mutator", [
    lambda m: [r["book_fill"].update(gb=10 ** 400) for r in m["days"] if r["day"] == "2025-01-02"],
    lambda m: m["meta"]["cost_model"].update(book_usd_per_gb=10 ** 400),
])
def test_huge_integer_literals_are_clean_input_errors(tmp_path, mutator):
    # json parses arbitrary-size ints; unbounded they crash float()/int() downstream — reject at
    # the load boundary like the reviewer does, never an OverflowError/ValueError traceback
    path, _ = fx.ready_manifest(tmp_path)
    fx.mutate_manifest(path, mutator)
    with pytest.raises(bf.BackfillInputError, match="integer"):
        _plan(path, verify_inputs=False)


def test_integer_beyond_cpython_digit_limit_is_clean_input_error(tmp_path):
    # >4300 digits trips the CPython str->int limit inside json parsing (raw text injection —
    # json.dump itself refuses to serialize such an int)
    path, _ = fx.ready_manifest(tmp_path)
    with open(path) as f:
        text = f.read()
    assert '"gb": 2.27' in text
    with open(path, "w") as f:
        f.write(text.replace('"gb": 2.27', '"gb": 1' + "0" * 5000, 1))
    with pytest.raises(bf.BackfillInputError, match="integer"):
        _plan(path, verify_inputs=False)


def test_refuses_blockers_object_missing_contract_keys(tmp_path):
    # blockers like coverage_gaps leave no days[]-level trace, so deleting their (non-empty) list
    # would silently unblock a manifest: the blockers object must carry the exact reviewer key set
    path, _ = fx.ready_manifest(tmp_path)
    fx.mutate_manifest(path, lambda m: m["blockers"].pop("coverage_gaps"))
    with pytest.raises(bf.BackfillRefusal, match="blocker"):
        _plan(path, verify_inputs=False)


@pytest.mark.parametrize("rate", [0, -1.0])
def test_refuses_nonpositive_cost_rates(tmp_path, rate):
    # a zero/negative rate would price the whole backfill at <= $0 and defeat the spend cap
    path, _ = fx.ready_manifest(tmp_path)
    fx.mutate_manifest(path, lambda m: m["meta"]["cost_model"].update(book_usd_per_gb=rate))
    with pytest.raises(bf.BackfillRefusal, match="cost_model"):
        _plan(path, verify_inputs=False)


def test_refuses_non_canonical_day_strings(tmp_path):
    # date.fromisoformat accepts compact forms like 20250102 on 3.11+; a non-canonical day (kept
    # consistent across days[] AND sections, so the cross-checks alone can't catch it) would
    # defeat duplicate detection and produce a non-canonical dt= partition
    path, _ = fx.ready_manifest(tmp_path)
    def compact(m):
        for r in m["days"]:
            if r["day"] == "2025-01-02":
                r["day"] = "20250102"
        for k, days in m["sections"].items():
            m["sections"][k] = sorted("20250102" if d == "2025-01-02" else d for d in days)
    fx.mutate_manifest(path, compact)
    with pytest.raises(bf.BackfillRefusal, match="day"):
        _plan(path, verify_inputs=False)


def test_load_returns_manifest_and_hash_of_the_same_bytes(tmp_path):
    # single read: the sha256 the plan/pin/resume attest must be of the bytes that were parsed
    path, _ = fx.ready_manifest(tmp_path)
    manifest, sha = bf.load_reviewed_manifest(str(path))
    assert manifest["meta"]["status"] == "ready"
    assert sha == bf.sha256_file(str(path))


def test_plan_is_deterministic(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    a = _plan(path)
    b = _plan(path)
    assert json.dumps(a, sort_keys=True) == json.dumps(b, sort_keys=True)


def test_accepts_matching_pinned_hash(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    plan = _plan(path, expected_sha256=bf.sha256_file(str(path)))
    assert plan["totals"]["n_units"] == 5


def test_refuses_stale_pinned_inputs(tmp_path):
    path, manifest = fx.ready_manifest(tmp_path)
    cal_path = manifest["meta"]["inputs"]["usable_calendar"]["path"]
    with open(cal_path) as f:
        cal = json.load(f)
    cal["anchor_end"] = "2026-07-01"                     # regenerated since review
    with open(cal_path, "w") as f:
        json.dump(cal, f)
    with pytest.raises(bf.BackfillRefusal, match="stale"):
        _plan(path)


def test_refuses_missing_pinned_input(tmp_path):
    path, manifest = fx.ready_manifest(tmp_path)
    os.remove(manifest["meta"]["inputs"]["batch_reports"][0]["path"])
    with pytest.raises(bf.BackfillRefusal, match="stale"):
        _plan(path)


def test_refuses_excluded_day_with_fill(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    def poison(m):
        for r in m["days"]:
            if r["day"] == "2025-01-20":
                r["book_fill"]["needed"] = True
    fx.mutate_manifest(path, poison)
    with pytest.raises(bf.BackfillRefusal, match="excluded"):
        _plan(path, verify_inputs=False)


def test_refuses_duplicate_day_records(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    fx.mutate_manifest(path, lambda m: m["days"].append(dict(m["days"][1])))
    with pytest.raises(bf.BackfillRefusal, match="duplicate"):
        _plan(path, verify_inputs=False)


def test_refuses_sections_drift(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    fx.mutate_manifest(path, lambda m: m["sections"]["trade_fills"].remove("2025-01-11"))
    with pytest.raises(bf.BackfillRefusal, match="section"):
        _plan(path, verify_inputs=False)


def test_refuses_cost_summary_drift(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    fx.mutate_manifest(
        path, lambda m: m["cost_summary"].update(book_gb_total=m["cost_summary"]["book_gb_total"] + 1))
    with pytest.raises(bf.BackfillRefusal, match="cost"):
        _plan(path, verify_inputs=False)


def test_refuses_fill_unit_without_executable_stitch_plan(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    def strip_plan(m):
        for r in m["days"]:
            if r["day"] == "2025-01-02":
                r["book_fill"]["fill_segments"] = []
    fx.mutate_manifest(path, strip_plan)
    with pytest.raises(bf.BackfillRefusal, match="segment"):
        _plan(path, verify_inputs=False)


def test_load_input_errors_are_input_errors(tmp_path):
    with pytest.raises(bf.BackfillInputError):
        bf.load_reviewed_manifest(str(tmp_path / "nope.json"))
    bad = tmp_path / "bad.json"
    bad.write_text("{not json")
    with pytest.raises(bf.BackfillInputError):
        bf.load_reviewed_manifest(str(bad))
    arr = tmp_path / "arr.json"
    arr.write_text("[1,2]")
    with pytest.raises(bf.BackfillInputError):
        bf.load_reviewed_manifest(str(arr))


# =========================================================================== pilot window
def test_pilot_window_subset_is_deterministic_and_hash_pinned(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    full = _plan(path)
    sub = _plan(path, window_start="2025-01-10", window_end="2025-01-11")
    keys = [(u["product"], u["day"]) for u in sub["units"]]
    assert keys == [("limitbook_full", "2025-01-10"), ("trades", "2025-01-10"),
                    ("trades", "2025-01-11")]
    assert sub["meta"]["window"] == {"start": "2025-01-10", "end": "2025-01-11"}
    assert sub["meta"]["manifest"]["sha256"] == full["meta"]["manifest"]["sha256"]
    # fill policy NOT recomputed: subset units carry the identical provenance/cost rows
    fu, su = _units_by_key(full), _units_by_key(sub)
    for k in keys:
        assert su[k] == fu[k]
    # subset totals are sums over the selected units only
    assert sub["totals"]["n_units"] == 3
    assert sub["totals"]["book_gb_total"] == 1.0
    assert sub["totals"]["trades_gb_total"] == 0.05
    assert sub["totals"]["gross_usd"] == round(1.0 * 1.0 + 0.05 * 3.0, 4)
    # the FULL scope still reconciles against the manifest even when a window is applied
    assert sub["reconciliation"]["matches_manifest_cost_summary"] is True
    assert sub["scope"]["skipped_by_window"] == 2


def test_pilot_window_rejects_empty_or_invalid_selection(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    with pytest.raises(bf.BackfillInputError, match="window"):
        _plan(path, window_start="2025-02-01", window_end="2025-02-02")
    with pytest.raises(bf.BackfillInputError, match="window"):
        _plan(path, window_start="2025-01-11", window_end="2025-01-10")
    with pytest.raises(bf.BackfillInputError, match="window"):
        _plan(path, window_start="not-a-date", window_end="2025-01-10")
    with pytest.raises(bf.BackfillInputError, match="window"):
        _plan(path, window_start="2025-01-10", window_end=None)


# =========================================================================== resume keying
def test_state_path_keys_on_source_product_day_and_fingerprint(tmp_path):
    sha = "a" * 64
    p = bf.state_path(str(tmp_path), sha, "limitbook_full", "2025-01-02")
    assert sha in p and "coinapi_flatfiles" in p and "limitbook_full" in p and "2025-01-02" in p
    other = bf.state_path(str(tmp_path), "b" * 64, "limitbook_full", "2025-01-02")
    assert other != p


def _final(tmp_path, content=b"parquet-bytes"):
    final = tmp_path / "part" / "data.parquet"
    final.parent.mkdir(parents=True, exist_ok=True)
    final.write_bytes(content)
    return str(final)


def _ok_state(content=b"parquet-bytes"):
    import hashlib
    return {"status": "ok", "out_bytes": len(content),
            "out_sha256": hashlib.sha256(content).hexdigest()}


def test_resume_semantics(tmp_path):
    sha, unit = "a" * 64, {"product": "limitbook_full", "day": "2025-01-02"}
    out = str(tmp_path)
    final = str(tmp_path / "part" / "data.parquet")
    # nothing on disk -> todo
    assert bf.unit_resume_status(out, sha, unit, final) == "todo"
    # state without output -> stale, must re-run
    bf.write_state(out, sha, unit, _ok_state())
    assert bf.unit_resume_status(out, sha, unit, final) == "todo"
    # matching state + output (size AND sha) -> done
    final = _final(tmp_path)
    assert bf.unit_resume_status(out, sha, unit, final) == "done"
    # size drift -> conflict (stale output cannot count as done)
    bf.write_state(out, sha, unit, {**_ok_state(), "out_bytes": 999})
    assert bf.unit_resume_status(out, sha, unit, final) == "conflict"


def test_resume_verifies_content_not_just_size(tmp_path):
    sha, unit = "a" * 64, {"product": "limitbook_full", "day": "2025-01-02"}
    out = str(tmp_path)
    final = _final(tmp_path)
    bf.write_state(out, sha, unit, _ok_state())
    assert bf.unit_resume_status(out, sha, unit, final) == "done"
    # same-size in-place drift must NOT count as done — the state vouches for exact bytes
    _final(tmp_path, content=b"PARQUET-BYTES")
    assert bf.unit_resume_status(out, sha, unit, final) == "conflict"
    # a state record without an out_sha256 cannot vouch either (fail-closed)
    _final(tmp_path)
    bf.write_state(out, sha, unit, {"status": "ok", "out_bytes": 13})
    assert bf.unit_resume_status(out, sha, unit, final) == "conflict"


def test_resume_is_manifest_fingerprint_scoped(tmp_path):
    unit = {"product": "limitbook_full", "day": "2025-01-02"}
    out = str(tmp_path)
    final = _final(tmp_path)
    bf.write_state(out, "a" * 64, unit, _ok_state())
    assert bf.unit_resume_status(out, "a" * 64, unit, final) == "done"
    # a DIFFERENT manifest fingerprint owns no state for this output -> conflict, fail closed
    assert bf.unit_resume_status(out, "b" * 64, unit, final) == "conflict"


def test_existing_output_without_state_is_conflict_unless_overwrite(tmp_path):
    sha, unit = "a" * 64, {"product": "trades", "day": "2025-01-10"}
    final = _final(tmp_path)
    assert bf.unit_resume_status(str(tmp_path), sha, unit, final) == "conflict"
    assert bf.unit_resume_status(str(tmp_path), sha, unit, final, overwrite=True) == "todo"


# =========================================================================== execution report
def _result(unit, status, **kw):
    base = {"source": "coinapi_flatfiles", "product": unit["product"], "day": unit["day"],
            "kind": unit.get("kind", "full_day"), "status": status, "key": None,
            "src_bytes": 0, "src_sha256": None, "rows": 0, "out_bytes": 0, "out_sha256": None,
            "out_path": None, "secs": 0.0, "error": None}
    base.update(kw)
    return base


def test_execution_report_reconciles(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    plan = _plan(path)
    units = plan["units"]
    results = [
        _result(units[0], "ok", src_bytes=1_000_000, src_sha256="s0", rows=10,
                out_bytes=500, out_sha256="o0", out_path="x", key="k0"),
        _result(units[1], "ok", src_bytes=2_000_000, src_sha256="s1", rows=20,
                out_bytes=600, out_sha256="o1", out_path="y", key="k1"),
        _result(units[2], "done"),
        _result(units[3], "missing"),
        _result(units[4], "error", error="boom"),
    ]
    spend = {"approve_usd": 10.0, "spend_evidence": "issue #33 approval",
             "allow_backfill": True}
    report = bf.build_execution_report(plan, results, spend=spend,
                                       generated_utc="2026-07-10T02:00:00Z")
    rec = report["reconciliation"]
    assert rec["planned"] == 5 and rec["accounted"] == 5
    assert rec["ok"] == 2 and rec["done_prior"] == 1 and rec["missing"] == 1
    assert rec["error"] == 1 and rec["conflict"] == 0
    assert rec["complete"] is False
    assert rec["bytes_downloaded"] == 3_000_000
    assert rec["rows_written"] == 30
    assert report["spend"]["approve_usd"] == 10.0
    assert report["spend"]["spend_evidence"] == "issue #33 approval"
    assert report["spend"]["planned_usd_high"] == plan["totals"]["usd_high"]
    assert report["meta"]["manifest"]["sha256"] == plan["meta"]["manifest"]["sha256"]
    assert len(report["units"]) == 5
    # every unit result keeps its provenance hash fields for the audit trail
    assert report["units"][0]["src_sha256"] == "s0" and report["units"][0]["out_sha256"] == "o0"


def test_execution_report_complete_when_all_ok_or_done(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    plan = _plan(path)
    results = [_result(u, "ok", src_bytes=10, rows=1) for u in plan["units"][:-1]]
    results.append(_result(plan["units"][-1], "done"))
    report = bf.build_execution_report(plan, results, spend={"approve_usd": 6.0},
                                       generated_utc="2026-07-10T02:00:00Z")
    assert report["reconciliation"]["complete"] is True


def test_report_refuses_unaccounted_units(tmp_path):
    path, _ = fx.ready_manifest(tmp_path)
    plan = _plan(path)
    results = [_result(u, "ok") for u in plan["units"][:-1]]   # one planned unit missing
    report = bf.build_execution_report(plan, results, spend={},
                                       generated_utc="2026-07-10T02:00:00Z")
    assert report["reconciliation"]["complete"] is False
    assert report["reconciliation"]["accounted"] == 4
    assert report["reconciliation"]["unaccounted_units"] == ["trades/2025-01-11"]


def test_report_reconciles_result_identity_not_just_counts(tmp_path):
    # a duplicated result for one unit plus a dropped unit keeps the COUNTS balanced (5 results,
    # 5 planned, all ok) — identity reconciliation must still flag the run incomplete
    path, _ = fx.ready_manifest(tmp_path)
    plan = _plan(path)
    results = [_result(u, "ok") for u in plan["units"][:-1]]
    results.append(_result(plan["units"][0], "ok"))            # duplicate, not the missing unit
    report = bf.build_execution_report(plan, results, spend={},
                                       generated_utc="2026-07-10T02:00:00Z")
    rec = report["reconciliation"]
    assert rec["complete"] is False
    assert rec["duplicate_results"] == ["limitbook_full/2025-01-02"]
    assert rec["unaccounted_units"] == ["trades/2025-01-11"]
    # a result for a unit the plan never contained is unplanned
    results2 = [_result(u, "ok") for u in plan["units"]]
    results2.append(_result({"product": "trades", "day": "2025-03-01"}, "ok"))
    rec2 = bf.build_execution_report(plan, results2, spend={},
                                     generated_utc="2026-07-10T02:00:00Z")["reconciliation"]
    assert rec2["complete"] is False
    assert rec2["unplanned_results"] == ["trades/2025-03-01"]


def test_report_units_carry_provenance_verbatim(tmp_path):
    # stitch metadata must survive into the EXECUTION report, not just the plan
    path, manifest = fx.ready_manifest(tmp_path)
    plan = _plan(path)
    results = [_result(u, "ok") for u in plan["units"]]
    report = bf.build_execution_report(plan, results, spend={},
                                       generated_utc="2026-07-10T02:00:00Z")
    by_key = {(u["product"], u["day"]): u for u in report["units"]}
    day = {r["day"]: r for r in manifest["days"]}
    partial = by_key[("limitbook_full", "2025-01-03")]
    assert partial["provenance"]["fill"] == day["2025-01-03"]["book_fill"]
    assert by_key[("trades", "2025-01-11")]["provenance"]["fill"] == day["2025-01-11"]["trade_fill"]
